# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af3bef52993db33e8571d131612a956b7e65a9ee3fea41f097fff7623ec79713688c87c492e086acaedc00647c9b88404ddb25f7c8b49cb379361ff5aa858872

test:
  secret_key_base: c3dd0770dad7434091866f65890d5c3b5ec300ee6b2634ec2df281e78aa90bd60288775555dad9e6cb6d77c98f0c256176558538347e5f83e041eb2edb21fbe0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
